### ISSUE TITLE
Unit tests for SG300

### ISSUE THREAD

**Issue by qaxi** [napalm-automation-community/napalm-s350#26]
write unit tests for SG300
**Todo:**
- [x] get_arp_table  #35 
- [x] get_arp_table_with_vrf #35 
- [x] get_config #35 
- [x] get_facts #36
- [x] get_interfaces #36
- [x] get_interfaces_ip #36
- [x] get_lldp_neighbors #36
- [x] get_lldp_neighbors_detail #36
- [x] get_ntp_servers #36
- [x] is_alive #36

**Comment by qaxi** [comment]
**Todo:**
- [x] get_arp_table  #35 
- [x] get_arp_table_with_vrf #35 
- [x] get_config #35 
- [ ] get_facts
- [ ] get_interfaces
- [ ] get_interfaces_ip
- [ ] get_lldp_neighbors
- [ ] get_lldp_neighbors_detail
- [ ] get_ntp_servers
- [ ] is_alive

**Comment by Phill93** [comment]
see #36
